repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-added-large-files
    - id: no-commit-to-branch
      args: [--branch, gh-pages]
    - id: check-yaml
    - id: detect-private-key
